name: Build Development Branch
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Build BB Dev Admin
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: replace Evironment
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./src/environments/environment.prod.ts"
          FILE_DATA: "${{ secrets.ENVIRONMENT }}"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add the host key
        run: |
          line='${{ secrets.KNOWN_HOSTS }}'
          echo "$line" >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          ls -la
          rsync -avz -e ssh ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/htdocs/dev/blackbeetle-admin/
      

 